# Calculo de D = C^T d C

Este notebook calcula a matriz `D = C^T d C` fazendo uma saida de `D` por vez.

Para cada coluna `j` de `C`:

1. Calcula-se a coluna intermediaria `D'[:, j] = d C[:, j]`, multiplicando cada linha de `d` pela coluna `j` de `C`.
2. Essa coluna intermediaria e entao multiplicada pelas linhas de `C^T`, gerando uma coluna de `D`.


In [1]:
import numpy as np

C = np.array([
    [1,  0, -1,  0],
    [0,  1,  1,  0],
    [0, -1,  1,  0],
    [0,  1,  0, -1],
], dtype=int)

d = np.array([
    [ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11],
    [12, 13, 14, 15],
], dtype=int)

print("C =")
print(C)
print("\nd =")
print(d)
print("\nC^T =")
print(C.T)


C =
[[ 1  0 -1  0]
 [ 0  1  1  0]
 [ 0 -1  1  0]
 [ 0  1  0 -1]]

d =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

C^T =
[[ 1  0  0  0]
 [ 0  1 -1  1]
 [-1  1  1  0]
 [ 0  0  0 -1]]


In [2]:
def dot_expression(a, b):
    return " + ".join(f"({x})*({y})" for x, y in zip(a, b))

def print_column_step(j, intermediate_col, output_col):
    print(f"Coluna {j} de C:")
    print(C[:, j])
    print(f"\n1) Calculando D'[:, {j}] = d C[:, {j}]")

    for row in range(d.shape[0]):
        expr = dot_expression(d[row, :], C[:, j])
        print(f"D'[{row}, {j}] = {expr} = {intermediate_col[row]}")

    print(f"\nD'[:, {j}] = {intermediate_col.tolist()}")
    print(f"\n2) Calculando D[:, {j}] = C^T D'[:, {j}]")

    for row in range(C.T.shape[0]):
        expr = dot_expression(C.T[row, :], intermediate_col)
        print(f"D[{row}, {j}] = {expr} = {output_col[row]}")

    print(f"\nD[:, {j}] = {output_col.tolist()}")


## Saida por saida

A matriz `D' = d C` nao precisa ser formada inteira de uma vez. Abaixo, cada coluna de `D'` e calculada separadamente e imediatamente usada para produzir a coluna correspondente de `D`.

In [3]:
D = np.zeros((4, 4), dtype=int)
intermediate_columns = []

for j in range(C.shape[1]):
    intermediate_col = d @ C[:, j]
    output_col = C.T @ intermediate_col

    D[:, j] = output_col
    intermediate_columns.append(intermediate_col)

    print("=" * 70)
    print_column_step(j, intermediate_col, output_col)
    print()


Coluna 0 de C:
[1 0 0 0]

1) Calculando D'[:, 0] = d C[:, 0]
D'[0, 0] = (0)*(1) + (1)*(0) + (2)*(0) + (3)*(0) = 0
D'[1, 0] = (4)*(1) + (5)*(0) + (6)*(0) + (7)*(0) = 4
D'[2, 0] = (8)*(1) + (9)*(0) + (10)*(0) + (11)*(0) = 8
D'[3, 0] = (12)*(1) + (13)*(0) + (14)*(0) + (15)*(0) = 12

D'[:, 0] = [0, 4, 8, 12]

2) Calculando D[:, 0] = C^T D'[:, 0]
D[0, 0] = (1)*(0) + (0)*(4) + (0)*(8) + (0)*(12) = 0
D[1, 0] = (0)*(0) + (1)*(4) + (-1)*(8) + (1)*(12) = 8
D[2, 0] = (-1)*(0) + (1)*(4) + (1)*(8) + (0)*(12) = 12
D[3, 0] = (0)*(0) + (0)*(4) + (0)*(8) + (-1)*(12) = -12

D[:, 0] = [0, 8, 12, -12]

Coluna 1 de C:
[ 0  1 -1  1]

1) Calculando D'[:, 1] = d C[:, 1]
D'[0, 1] = (0)*(0) + (1)*(1) + (2)*(-1) + (3)*(1) = 2
D'[1, 1] = (4)*(0) + (5)*(1) + (6)*(-1) + (7)*(1) = 6
D'[2, 1] = (8)*(0) + (9)*(1) + (10)*(-1) + (11)*(1) = 10
D'[3, 1] = (12)*(0) + (13)*(1) + (14)*(-1) + (15)*(1) = 14

D'[:, 1] = [2, 6, 10, 14]

2) Calculando D[:, 1] = C^T D'[:, 1]
D[0, 1] = (1)*(2) + (0)*(6) + (0)*(10) + (0)*(14) = 2
D[

## Resultado final

In [4]:
D_prime = np.column_stack(intermediate_columns)
D_direct = C.T @ d @ C

print("D' = d C =")
print(D_prime)
print("\nD = C^T D' = C^T d C =")
print(D)

assert np.array_equal(D, D_direct)
print("\nVerificacao: D e igual a C^T @ d @ C.")


D' = d C =
[[  0   2   3  -3]
 [  4   6   7  -7]
 [  8  10  11 -11]
 [ 12  14  15 -15]]

D = C^T D' = C^T d C =
[[  0   2   3  -3]
 [  8  10  11 -11]
 [ 12  14  15 -15]
 [-12 -14 -15  15]]

Verificacao: D e igual a C^T @ d @ C.
